### ISSUE TITLE
correct filesystem value

### ISSUE THREAD

**Issue by ntap-johanneswagner** [redhat-gpst/rosa-fsx-lab-guide#10]
https://github.com/redhat-gpst/rosa-fsx-lab-guide/blob/main/fsx/storage-class-csi-nas.yml

`  fsType: "ext4" `
might be very misleading as the filesystem will ever be "nfs" for this driver. However it's important to specify "csi.storage.k8s.io/fstype" as otherwise k8s would ignore any fsgroup setting in the pod as it would assume that there is no filesystem existing. I would use 

`csi.storage.k8s.io/fstype: “nfs”`

**Comment by ntap-johanneswagner** [comment]
@rbo

**Comment by rbo** [comment]
@ntap-johanneswagner or we can remove it entirely? 

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trident-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
allowVolumeExpansion: True
reclaimPolicy: Retain
```

Should be good to go?

**Comment by ntap-johanneswagner** [comment]
@rbo reading is something important... 

> However it's important to specify "csi.storage.k8s.io/fstype" as otherwise k8s would ignore any fsgroup setting in the pod as it would assume that there is no filesystem existing.

For your lab it should work, however I would recommend to do the clean way.

**Comment by rbo** [comment]
@ntap-johanneswagner the official docution looks like this:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
```
Source: https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_trident_ontap_nfs.html

I just removed the `fsType` 

Thanks for the issue.
