### ISSUE TITLE
Change default StorageClass from  from GP3 to trident-csi

### ISSUE THREAD

**Issue by fabian-born** [redhat-gpst/rosa-fsx-lab-guide#7]
Change Storage Class: Make Trident as default

```
    oc patch storageclass gp3 -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
```
```
    oc patch storageclass trident-csi -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```

or
```

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trident-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  fsType: "ext4"
allowVolumeExpansion: True
reclaimPolicy: Retain
```
