### ISSUE TITLE
change retain policy

### ISSUE THREAD

**Issue by fabian-born** [redhat-gpst/rosa-fsx-lab-guide#8]
https://github.com/redhat-gpst/rosa-fsx-lab-guide/blob/main/fsx/storage-class-csi-nas.yml

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trident-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  fsType: "ext4"
allowVolumeExpansion: True
reclaimPolicy: Delete
```
Cause: After removing a PV/PVC the volume will be still available on FSxN
